apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
  labels: 
    gits.k8s.cluster: cluster-0
spec:
  server:
    route:
      enabled: true
  dex:
    image: quay.io/redhat-cop/dex
    openShiftOAuth: true
    version: v2.22.0-openshift
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      p, role:subtenant-1-admin, applications, *, */*, allow
      p, role:subtenant-1-admin, clusters, get, *, allow
      p, role:subtenant-1-admin, repositories, get, *, allow

      p, role:subtenant-3-admin, applications, *, subtenant-3/*, allow
      p, role:subtenant-3-admin, clusters, get, *, allow
      p, role:subtenant-3-admin, repositories, get, *, allow

      g, mygroup1, role:subtenant-1-admin
      g, mygroup3, role:subtenant-3-admin
      g, mysupergroup, role:admin
      g, system:cluster-admins, role:admin
    scopes: '[groups]'
  initialRepositories: |
    - name: api-gw-subtenant
      sshPrivateKeySecret:
        key: sshPrivateKey
        name: repo-2643070425
      type: git
      url: git@github.com:sadhal/api-gw-subtenant.git
    - type: git
      url: https://github.com/sadhal/multi-tenancy-team0-api-gw
    - type: git
      url: https://github.com/sadhal/tenant-x

