apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-projects-reconciler-cluster-0
  namespace: argocd
spec:
  destination:
    namespace: '*'
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: overlays/cluster-0/
    repoURL: 'https://github.com/sadhal/tenant-x-argocd'
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true