apiVersion: batch/v1
kind: Job
metadata:
  # generateName: subtenant-1-rocketchat-notification-success-
  name: subtenant-1-rocketchat-notification-success
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: curlimages/curl
        command: 
          - "curl"
          - "-X"
          - "POST"
          - "--data-urlencode"
          - "payload={\"channel\": \"#somechannel\", \"username\": \"hello\", \"text\": \"App Sync succeeded\", \"icon_emoji\": \":heart:\"}"
          - "https://httpbin.org/anything"
          - "-v"
      restartPolicy: Never
  backoffLimit: 2